[project]
name = "comfyuidepthestimation"
description = "A custom depth estimation node for ComfyUI using transformer models. It integrates depth estimation with automatic gamma correction, contrast adjustment, and edge detection, based on the [a/TransformDepth](https://github.com/Limbicnation/TransformDepth) repository."
version = "1.0.0"
license = { file = "LICENSE" }
dependencies = ["transformers==4.12.3", "Pillow==8.4.0", "numpy==1.21.2", "# Add other necessary dependencies without specifying torch again"]

[project.urls]
Repository = "https://github.com/Limbicnation/ComfyUIDepthEstimation"
#  Used by Comfy Registry https://comfyregistry.org

[tool.comfy]
PublisherId = ""
DisplayName = "ComfyUIDepthEstimation"
Icon = ""
